### PR TITLE
refactor: remove createDatabase, add return errors

### LINKED ISSUE #5: panic: interface conversion: *beegoormadapter.Adapter is not persist.Adapter: missing method LoadPolicy
I have problem when run my app I catch error: "panic: interface conversion: *beegoormadapter.Adapter is not persist.Adapter: missing method LoadPolicy
". 

My dependencies:
Go 1.14
github.com/casbin/beego-orm-adapter v0.0.0-20180421160615-ba104911ae5b
github.com/casbin/casbin/v2 v2.2.1

What problem is it?

### PR DESCRIPTION
**Pull request by nodece**
Fix: https://github.com/casbin/beego-orm-adapter/issues/5

### CODE REVIEW

**Comment by hsluoyz** [comment]
CI failed.

**Comment by nodece** [comment]
@hsluoyz , fixed

**Comment by hsluoyz** [comment]
lgtm

**Comment by MaksNech** [comment]
@hsluoyz @nodece  Hi collegues, the problem is still not resolved.
I created a new empty project to test the compatibility of work casbin v2 with beego-orm-adapter. When I set dependencies using Go modules I catch next error:
Screen Shot 2020-03-20 at 1 42 47 PM
After that my go.mod file looks like this:
Screen Shot 2020-03-20 at 1 44 33 PM
I really hope that you did not remove the Postgres database support from the beego-orm-adapter, since our application runs on Postgres.
One more question: Is it possible to use an existing database for the table "casbin_rule" and not create a new one instead? And how can I turn off auto-migrations when run initializing the beego-orm-adapter?

**Comment by nodece** [comment]
Sorry @MaksNech, because I defined an error module.

**Comment by hsluoyz** [comment]
@nodece can we add back the PostgreSQL example code in README like this one? https://github.com/casbin/xorm-adapter

I saw you deleted it but don't know why.

**Comment by nodece** [comment]
@hsluoyz Just provide an example, I feel relatively clean.

**Comment by MaksNech** [comment]
@hsluoyz @nodece  Sorry, but it still doesn't install correctly through Go modules:
Catch the same message:
Screen Shot 2020-03-20 at 6 50 14 PM

My go.mod file still without beego-orm-adapter/v2:
Screen Shot 2020-03-20 at 6 55 03 PM
With  Regardness.

**Comment by hsluoyz** [comment]
Let's discuss only here: https://github.com/casbin/beego-orm-adapter/issues/5#issuecomment-601815481

**Pull request merged**
